### ISSUE TITLE
Waterfox generates error during apt-get update

### ISSUE THREAD

**Issue by graciecat** [hawkeye116477/waterfox-deb#1]
I followed the instructions at: https://hawkeye116477.github.io/waterfox-deb/ .

When I did `sudo apt-get update` I got the following error message:

`W: Failed to fetch https://hawkeye116477.github.io/waterfox-deb/dists/release/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
`

Using Ubuntu 14.04.5

**Comment by hawkeye116477** [comment]
Waterfox is only 64-bit. If you have a 32-bit system, then Waterfox will not work.

**Comment by graciecat** [comment]
My OS is 64-bit Ubuntu 14.0.4 ! So apparently something is not correctly installed?

**Comment by hawkeye116477** [comment]
Add [arch=amd64] to entry in /etc/apt/sources.list.d/waterfox-release-hawkeye116477.list . 
This should look like this --> deb [arch=amd64] https://hawkeye116477.github.io/waterfox-deb release main

**Comment by graciecat** [comment]
That did help me, before you changed your repository. Thanks.
