### ISSUE TITLE
32bit compilation?

### ISSUE THREAD

**Issue by pirate486743186** [hawkeye116477/waterfox-deb#10]
lol.... what happens when you try to compile in 32bit ?

**Comment by hawkeye116477** [comment]
I will see. I didn't tried that yet.

**Comment by hawkeye116477** [comment]
Unfortunately `error: failed to run custom build command for `style v0.0.1 (file:///usr/src/packages/BUILD/servo/components/style)` just like on Trusty 64-bit.

**Comment by hawkeye116477** [comment]
Hmm, I will see. I can probably add condtion to mozconfig.
```
codename=$(lsb_release -sc)
arch=$(getconf LONG_BIT)
if ! [ "$codename" = "trusty" ] || ! [ "$arch" = "32" ]; then
ac_add_options --enable-stylo=build
fi
```
So if it's Trusty or 32-bit, then stylo should be disabled.

**Comment by pirate486743186** [comment]
I tested it on 18.04 and it seams ok.... apart the fact the 64 bit repo is broken XD lol

You should add in it's description, that the 32 bit version is unsupported.

**Comment by pirate486743186** [comment]
it still crashes with multiprocess disabled?

**Comment by hawkeye116477** [comment]
I didn't see if they are using special patches, but they are using GCC, I'm Clang, LLVM, for Trusty I must use Clang-3.9 unfortunately, as no newer version if official Trusty repos.

**Comment by pirate486743186** [comment]
Try the same version of gcc they are using.
Same for the 32 bit versions that don't compile.
Try to see if stylo compiles under gcc.

Why are you using clang? Changing compilers, even slightly different versions of the same compiler can lead to problem. They always interpret things slightly differently. New bugs can be introduced even if the program compiles. The best practice, is to stick as close as possible, to whatever the original programmer used.

**Comment by hawkeye116477** [comment]
@pirate486743186 I'm using Clang, because official Waterfox is also compiled with Clang, I see that even this is Clang 3.9.1, interesting because I used the same for Trusty. So this is probably must not be problem with Clang.

**Comment by hawkeye116477** [comment]
@pirate486743186 Unfortunately, same error. Maybe we need llvm-4.0 and that's why they are backported it to Trusty. But I'm curious how MrAlex compiled it with clang/llvm-3.9.1, maybe he had fix for that, but forgot to push to GH.

**Comment by pirate486743186** [comment]
Ubuntu has a dedicated team that makes sure firefox compiles properly on all supported platforms. That's too difficult to emulate alone....
 
Statically link and/or bundle libraries in a package of whatever version alex officially supports and repackage it for trusty. Do the same trick with 32 bit versions and all other versions that don't compile/work normally.

**Comment by hawkeye116477** [comment]
@pirate486743186 
I'm not trying to make it by myself. I can just use LLVM sources from PPA Mozilla Security Team (or http://apt.llvm.org/) and build it on OBS, so OBS should use it. It's just for me, for build, normal people don't need it :smile:

**Comment by hawkeye116477** [comment]
@pirate486743186 I tried compiling with gcc-mozilla and LLVM 4 (I rebuilt it with OBS) and checked and appears that all working fine. But problem is that it needs worker with more space, previously I set to 60 GB and failed with memory exhaustion error, now it's 90 GB, but only 2 workers on OBS meet the requirements, so version for Trusty will be always few hours later than others.

**Comment by pirate486743186** [comment]
you are still motivated for 32 bit?

**Comment by hawkeye116477** [comment]
Problem is that if I make it, then 64-bit Waterfox isn't visible on Synaptic by default, we must click architectures-amd64 and then we must scroll to see Waterfox 64-bit. That can cause confusion. However command `sudo apt install waterfox` working fine, so I'm not sure what to do with it.
Also 32-bit isn't officially supported, so maybe more problems. For now I'm resigns with that idea.
However you can always make account on OBS and fork my project (Branch package).

**Comment by pirate486743186** [comment]
Can you at least make a 32bit appimage?
Yes, i know it's not officially supported and they are no guarantees....

**Comment by pirate486743186** [comment]
You are planing to make a 64bit appimage package anyway, no?

**Comment by hawkeye116477** [comment]
@pirate486743186 AppImage for 64-bit I already made, but for now it's just repackaged official version => `https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/Waterfox-latest-x86_64.AppImage.mirrorlist`.
