### ISSUE TITLE
Weird repo bug

### ISSUE THREAD

**Issue by pirate486743186** [hawkeye116477/waterfox-deb#11]
You somehow broke the repo when you uploaded the 32bit version. It seams the 32 bit packages are masking the 64 bit ones inside apt.

In the 32 bit system, things are fine.
In 64 bit, i see the 32 bit packages only.

**Comment by hawkeye116477** [comment]
That's strange, I checked and all is fine.

**Comment by pirate486743186** [comment]
i'm not an expert,just a power user. I'm just guessing.

I think you messed up the conflict/replaces flags and apt and synaptic go nuts

In the locals it seams to say that they conflict with the "64bit" versions. I suppose it thinks the 32 bit version is the newer one, so it masks the "old" ones. In waterfox:i386 it sais it conflicts with waterfox and did the same thing. in waterfox-kde it has "replaces waterfox" ...twice even, so it treated it like waterfox....

You don't need to change their name, packages of different architectures can have the same name. Normal ubuntu repos give access to i386 versions of packages,if they exist with out a problem like this. The name spaces of architecture are on parallel universes, so you don't need to manage dependencies between them.

If you try to search for waterfox in synaptic,what do you get?
remove the 32 bit stuff to see if that fixes that?

when i do "sudo apt install waterfox" i get:

The following NEW packages will be installed:
  kwayland-data kwayland-integration libdbusmenu-qt5-2 libfam0
  libkf5archive5 libkf5auth-data libkf5auth5 libkf5codecs-data
  libkf5codecs5 libkf5config-bin libkf5config-data libkf5configcore5
  libkf5configgui5 libkf5configwidgets-data libkf5configwidgets5
  libkf5coreaddons-data libkf5coreaddons5 libkf5crash5
  libkf5dbusaddons-bin libkf5dbusaddons-data libkf5dbusaddons5
  libkf5guiaddons5 libkf5i18n-data libkf5i18n5 libkf5iconthemes-bin
  libkf5iconthemes-data libkf5iconthemes5 libkf5idletime5
  libkf5itemviews-data libkf5itemviews5 libkf5notifications-data
  libkf5notifications5 libkf5service-bin libkf5service-data
  libkf5service5 libkf5wallet-bin libkf5wallet-data libkf5wallet5
  libkf5waylandclient5 libkf5widgetsaddons-data libkf5widgetsaddons5
  libkf5windowsystem-data libkf5windowsystem5 libkwalletbackend5-5
  libphonon4qt5-4 libpolkit-qt5-1-1 libqt5script5 libqt5texttospeech5
  libqt5xml5 phonon4qt5 phonon4qt5-backend-vlc waterfox

if i do:
"sudo dpkg -i waterfox_56.2.4-0_amd64.deb"
It doesn't try to install all that stuff

I'm assuming it messed up the dependencies with those of waterfox-kde with that "replace"

**Comment by hawkeye116477** [comment]
Check palemoon `https://software.opensuse.org//download.html?project=home%3Astevenpusser&package=palemoon`, same is on Palemoon, Synaptics shows as default only 32-bit packages

```
when i do "sudo apt install waterfox" i get:

The following NEW packages will be installed:
kwayland-data kwayland-integration libdbusmenu-qt5-2 libfam0
libkf5archive5 libkf5auth-data libkf5auth5 libkf5codecs-data
libkf5codecs5 libkf5config-bin libkf5config-data libkf5configcore5
libkf5configgui5 libkf5configwidgets-data libkf5configwidgets5
libkf5coreaddons-data libkf5coreaddons5 libkf5crash5
libkf5dbusaddons-bin libkf5dbusaddons-data libkf5dbusaddons5
libkf5guiaddons5 libkf5i18n-data libkf5i18n5 libkf5iconthemes-bin
libkf5iconthemes-data libkf5iconthemes5 libkf5idletime5
libkf5itemviews-data libkf5itemviews5 libkf5notifications-data
libkf5notifications5 libkf5service-bin libkf5service-data
libkf5service5 libkf5wallet-bin libkf5wallet-data libkf5wallet5
libkf5waylandclient5 libkf5widgetsaddons-data libkf5widgetsaddons5
libkf5windowsystem-data libkf5windowsystem5 libkwalletbackend5-5
libphonon4qt5-4 libpolkit-qt5-1-1 libqt5script5 libqt5texttospeech5
libqt5xml5 phonon4qt5 phonon4qt5-backend-vlc waterfox

I'm assuming it messed up the dependencies with those of waterfox-kde with that "replace"
```

Maybe, I don't have that bug. But ok, I'll remove replaces.

**Comment by pirate486743186** [comment]
Wait. I'm searching a bit, i think i was saying some nonsense earlier XD
Don't do anything yet. Don't remove replace.

I fond the error with the weird qt dependencies. Ubuntu by default installs recommended packages. So they should "suggest", not recommend waterfox-kde/waterfox.

I'm still looking into the 32/64 conflict

**Comment by pirate486743186** [comment]
lol, i don't see anything wrong in the 32 bit package XD .

**Comment by hawkeye116477** [comment]
Ok, I removed 32-bit packages, now it should show 64-bit packages by default.

**Comment by pirate486743186** [comment]
You should just change recommend to suggest for the next release.
That was unrelated to 32 bit. apt works as intended otherwise

I don't see any error.... for the 32bit thing.
I added the palemoon repo and it doesn't do that. I looked in it's control file, and it's basically the same....

You are seeing the same error right?
Readd it to see if its ok now? A server error? Otherwise it's just a bug in synaptic?

**Comment by hawkeye116477** [comment]
@pirate486743186 It's screenshot from Mint Tara 64-bit
![minttara64](https://user-images.githubusercontent.com/19818572/47378688-2b82e700-d6f9-11e8-95a3-902de62e4a62.PNG)
Now when I removed 32-bit waterfox, then it shows 64-bit by default.
For Palemoon I can click on Architecture button, then I choose amd64 and I must scroll up to see palemoon 64-bit, cuz if I just search palemoon, then thing from screenshot happens.

**Comment by pirate486743186** [comment]
I think, linux mint, doesn't install recommends by default.
I'm on vanilla ubuntu MATE 18.04
So that misery.... i mean mystery is solved.

About palemoon, i had loaded the 18.10 repo  instead of the 18.04 XD
so with 18.10 it doesn't do that.... O_o (just  change the number in the url)
with 18.04, it installs fine in apt. (with 18.10 repo, it complains about unmet dependencies as expected)

I also tried in "gnome-software" (like synaptic) and i couldn't find palemoon at all, it could find waterfox.

**Comment by pirate486743186** [comment]
You'll do what? Just ignore it? apt seams to work fine....

**Comment by pirate486743186** [comment]
i filled a bug report with obs
https://github.com/openSUSE/open-build-service/issues/6371
