### ISSUE TITLE
container packages

### ISSUE THREAD

**Issue by pirate486743186** [hawkeye116477/waterfox-deb#13]
You look motivated :P
I think it's a good idea to make a snap package.
If the normal package has some problem on some unusual distro, the people there can fall back on the snap, or just use the snap.

**Comment by pirate486743186** [comment]
In practice, it's going to be even more standards hell....

**Comment by pirate486743186** [comment]
Yea, have you taken in to consideration, that these packages need to be updated also when their libs get security fixes? Not only just when a new waterfox version comes out. That's true also for the appimage you just made.

**Comment by hawkeye116477** [comment]
If I read correct, then OBS should automatically publish newer version when libs got update. But user must manually update it or use libappimageupdate to set auto-update.

**Comment by pirate486743186** [comment]
I was guessing they would be doing that. One of the criticism of these formats, is that you are at the mercy of the packager to update the libs.

An other question. Are you sure you haven't bitten more then you can chew with all these packages?

**Comment by pirate486743186** [comment]
i meant, you might have took on too much stuff to do.....

**Comment by hawkeye116477** [comment]
@pirate486743186 You can try osc tool => `https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.osc.html`, it's just like a git for OBS, but commands are little different :smile:

**Comment by pirate486743186** [comment]
you gave me too much powers on OBS. I think i could just delete everything with out a trace.... You don't want to give so much power to random people. Frankly, i don't think i'll do any thing with it, so you can remove me.....

**Comment by hawkeye116477** [comment]
Ok
