### ISSUE TITLE
Which Ubuntu releases?

### ISSUE THREAD

**Issue by graciecat** [hawkeye116477/waterfox-deb#2]
Which Ubuntu releases does this repository support?

**Comment by hawkeye116477** [comment]
@graciecat This repository supports all Ubuntu LTS releases and Zesty Zapus of course. Probably also should be working on Yakkety Yak. But currently it requires libstdc++ 6.0.22, which isn't on some ubuntu versions, but you can do:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt upgrade
```
and libstdc++6 should be updated on Xenial.
On older versions I don't know if it works. For older versions try downloading newer libs from here: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/11037809. Download libgcc1, gcc-6-base and libstdc++6 and install them. If it break something, then don't install and unfortunately you must wait for update with fix. Alex works on it.

**Comment by hawkeye116477** [comment]
@graciecat I compiled waterfox and waterfox-kde with fix from @PandaCodex for libstdc++6. 
So you can download it from my new repo -> `echo "deb https://dl.bintray.com/hawkeye116477/waterfox-deb release main" | sudo tee /etc/apt/sources.list.d/waterfox-release-hawkeye116477.list`.
This also should be soon on old repo, but newer packages rather won't be on old repo, so I create something which add new repo link to users who already have old repo.

**Comment by graciecat** [comment]
@hawkeye116477 Ok, thanks. I will be writing a review. I had to add to the GNU C+ compiler libraries manually from the Launchpad repositories because I installed Waterfox before you changed your repository. The change should make things a lot easier.
