### ISSUE TITLE
Waterfox 56.2.8 lacks non-KDE build

### ISSUE THREAD

**Issue by IzzySoft** [hawkeye116477/waterfox-deb#24]
The KDE build (`waterfox-kde`) is available in the PPA, but it seems the non-KDE build (`waterfox`) is missing. Did something go wrong, or does it simply take a little longer? Just asking :wink:

PS: Thanks for providing the PPA!

**Comment by hawkeye116477** [comment]
@IzzySoft Oops, sorry, it's already built, but appears that I forgot to set publish flag. It should be available in a few minutes.

**Comment by IzzySoft** [comment]
Wow, if I've ever seen a fast reply, this was it. And I can update when I'm back home, cool! Thanks a lot!!! (Please close when done 😄)
