### ISSUE TITLE
Signature error.

### ISSUE THREAD

**Issue by Achaean** [hawkeye116477/waterfox-deb#25]
It used to work as expected, but the last time I got this (during "apt update" (as root)) at a Debian stable based distribution:

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/Debian_9.0  Release: The following signatures were invalid: EXPKEYSIG 5E62D791625A271E home:hawkeye116477 OBS Project <home:hawkeye116477@build.opensuse.org>
>

**Comment by hawkeye116477** [comment]
Just like I replied guy on reddit, try to add key again => https://www.reddit.com/r/waterfox/comments/c2dy40/signature_invalid/erjlkdo/ :smile:.

**Comment by Achaean** [comment]
Ooops! I missed that post!  :-)
**THANKS!!!**

**Comment by rubo77** [comment]
why not post it here?

```
wget -nv https://download.opensuse.org/repositories/home:hawkeye116477:waterfox/Debian_9.0/Release.key -O Release.key
apt-key add - < Release.key
sudo apt-key add - < Release.key
rm Release.key 
```
