### ISSUE TITLE
56.2.11 for xUbuntu_16.04 missing

### ISSUE THREAD

**Issue by IzzySoft** [hawkeye116477/waterfox-deb#26]
Will you build 56.2.11 for xUbuntu 16.04 as well? I see you already have it ready for 19.04 since June 20, and also for 18.04. With 16.04 being LTS and the base for Mint 18 (also LTS; supported until 4/2021), there's still demand for it there – especially with 56.2.11 containing a critical fix.

Thanks in advance!

**Comment by hawkeye116477** [comment]
Answer is here `https://www.reddit.com/r/waterfox/comments/c5uk21/ubuntu_and_debian_repository_problems/` :smile:

**Comment by IzzySoft** [comment]
Fast as always, thanks! Not being a "redditor" I didn't see that (though I fixed ① the signature thing by intuition about a week ago). I'll be patient then and hope the openSUSE team responds soon with a fix for ② (what I asked about here). 🤞

**Comment by hawkeye116477** [comment]
6 month ago I've problem with Debian Testing and admin replied 2 weeks after reporting the matter. 
So I hope that now we must wait 1 week (I reported that one week ago).

**Comment by hawkeye116477** [comment]
@IzzySoft Good news for you, they fixed that :smile:

**Comment by IzzySoft** [comment]
Yay, and there's the .deb already – cool, thanks! Now I only need to replace the icon :rofl:
