### ISSUE TITLE
Update failure.

### ISSUE THREAD

**Issue by Achaean** [hawkeye116477/waterfox-deb#29]
Update failed with the message that waterfox-classic-kde and kpe need for their installation the package waterfox-classic, which can't be installed (and there is not on the repository anyways).

**Comment by hawkeye116477** [comment]
What's your distro? Package waterfox-classic-kpe doesn't depend on waterfox-classic, it provides waterfox-classic, so should be good rather.

**Comment by Achaean** [comment]
Ooops! I forgot to mention it!  :-(
Sorry!!!  :-)

I'm (still) on Debian oldstable.

**Comment by denikris** [comment]
also happen when new install with `sudo apt install waterfox` on xubuntu 18.04.x

last line gave messages:
```
The following packages have unmet dependencies:
 waterfox : Depends: waterfox-classic
E: Unable to correct problems, you have held broken packages.
```

**Comment by hawkeye116477** [comment]
Sorry for that, appears that I forgot to change something in one file. Fix should be later today.

**Comment by parthabishwas** [comment]
==With Debian Testing Repository==
sudo apt-get install waterfox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 waterfox : Depends: waterfox-classic-kpe but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by hawkeye116477** [comment]
I know, same is for all distros. Please be patient, fix should be later today.

**Comment by hawkeye116477** [comment]
Looks like I identified problem, I added replaces and breaks tag as they suggested on `https://wiki.debian.org/Renaming_a_Package` and seems that doesn't work. 
So I'll do that without that tags.

**Comment by hawkeye116477** [comment]
Sorry, but appears that fix may be rather tomorrow, OBS made bad joke and doesn't want to publish packages, tells that's not picked up by scheduler yet.

**Comment by hawkeye116477** [comment]
I've good news, should be fixed now. Try updating again :smile:.

**Comment by IzzySoft** [comment]
Thanks for fixing and clarification – but on the other hand, this just got me confused: if "KPE" stands for "KDE Plasma Edition", does it depend on KDE libs? That would be bad for people especially running a light-weight install with e.g. XFCE. I wouldn't want half the KDE libs being drawn in just for that.

I just checked with `apt show waterfox-classic-kpe` – and luckily my fears where unjustified (no kde libs referenced in the dependencies as far as I can see). Unfortunately, I've got no "old DEB" here to compare, and the repo doesn't have it anymore either…

Maybe you could clarify this in the repo's README.md?

**Comment by hawkeye116477** [comment]
@IzzySoft It doesn't depend on KDE libs, patch contains communicating with kwaterfoxhelper, which depends on KDE libs.

`Maybe you could clarify this in the repo's README.md?`
Ok, I'll add explanation.

**Comment by IzzySoft** [comment]
Thanks @hawkeye116477 – for all 3: providing the DEB, explaining and adding the hint to the README! So basically, the transition is just for a change in the package name then, right? Unfortunately, at least Mint Updater only shows the meta-package and no details behind it.

**Comment by hawkeye116477** [comment]
@IzzySoft Not only package named changed, but also directory `/usr/lib/waterfox` => `/usr/lib/waterfox-classic` and binary now is named `waterfox-classic`.

**Comment by Achaean** [comment]
**THANKS!!!**  :-)
Everything seems to be OK now.

**Comment by IzzySoft** [comment]
@hawkeye116477 thanks! Apologies for my bad phrasing, that's about what I was referring to. Put in other words: not different/more dependencies etc. So my worries are all gone then :smile:
