### ISSUE TITLE
PLs help me out here...

### ISSUE THREAD

**Issue by gypsy-g** [hawkeye116477/waterfox-deb#5]
First a little background:
MX Linux Debian stretch 9.4
Waterfox was previously installed (I don't know where the installer is or where I got it) prior to a major crash. So I had to re-install it. Did that. But this is NOT how I want to run it. I don't want to have to keep an open terminal while using the browser. Waterfox appears nowhere in the program menu so I can't add any links to the panel. What's worse...I have no idea where this is all happening from (i.e where is waterfox? Neither whereis or locate tell me):
$ whereis waterfox
waterfox: /usr/bin/waterfox /usr/share/man/man1/waterfox.1.gz
This is the previous installation!

:~$ ls -al
drwx------  4 [redacted]   4096 Mar 14 21:48 .waterfox
This is the previous installation! Where is the program executable???

 or how to UNDO it. I appreciate the effort, but I've gotten frustrated with programs (a) without ANY instructions (waterfox has NO README) (b) no installers or uninstallers (c) too may download sites and empty forums or forums full of people with no clue or way to contact the developer(s)...whoever they are, please...don't start another project until one is complete.

**Comment by gypsy-g** [comment]
Never mind I think I've fixed it.

**Comment by hawkeye116477** [comment]
Hmm... If you installed it from my deb package/apt repository, then it should be on menu start. But I have no access to your PC and I don't know what you did. Waterfox binary should be in /usr/bin/waterfox and other waterfox files in opt/waterfox, but that is on my deb package and can be uninstalled from package manager or just `apt remove waterfox`.
