### ISSUE TITLE
No valid OpenPGP data found

### ISSUE THREAD

**Issue by dixonge** [hawkeye116477/waterfox-deb#6]
This is the error I get when trying to curl the public key

Kubuntu 18.04
64-bit

**Comment by hawkeye116477** [comment]
I checked on Kubuntu 18.04 and it's working fine.
You can also try downloading it with wget => `wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=hawkeye116477 | sudo apt-key add -`.

**Comment by pepoluan** [comment]
@dixonge are you using zsh? I use zsh and it seems zsh is a bit 'aggressive' trying to do wildcard matching on `?`.

Anyways, try wrap the URL between quotes and you should be good to go:

    curl 'https://bintray.com/user/downloadSubjectPublicKey?username=hawkeye116477' | sudo apt-key add -

**Comment by dixonge** [comment]
Yes, I am using zsh. Thanks!
