### ISSUE TITLE
Unable to locate package waterfox

### ISSUE THREAD

**Issue by volomike** [hawkeye116477/waterfox-deb#7]
I run the commands from the readme.md and get the following error in Ubuntu Linux 16.04:

E: Unable to locate package waterfox

**Comment by hawkeye116477** [comment]
Have you installed curl? Also try `wget -O - https://bintray.com/user/downloadSubjectPublicKey?username=hawkeye116477 | sudo apt-key add -`, then `sudo apt-get update` and then try install waterfox again :smile:.
