### ISSUE TITLE
Bug trying to update

### ISSUE THREAD

**Issue by dapper27** [hawkeye116477/waterfox-deb#8]
I just got the following warning after doing an update and upgrade. Is this a major problem? Any way I can keep waterfox as default without going through this every time I do an apt upgrade?

		The following packages will be upgraded:
		  waterfox{b}
		The following packages are RECOMMENDED but will NOT be installed:
		  waterfox-kde
		1 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
		Need to get 41.3 MB of archives. After unpacking 877 kB will be used.
		The following packages have unmet dependencies:
		 waterfox : Depends: libdbus-1-3 (>= 1.9.14) but 1.6.18-0ubuntu4.5 is installed.
					Depends: libfontconfig1 (>= 2.11.94) but 2.11.0-0ubuntu4.2 is installed.
					Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.4 is installed.
		The following actions will resolve these dependencies:

			 Remove the following packages:
		1)     waterfox

		Accept this solution? [Y/n/q/?] n
		The following actions will resolve these dependencies:

			 Keep the following packages at their current version:
		1)     waterfox [56.2.3 (now, release)]

		Accept this solution? [Y/n/q/?] y
		No packages will be installed, upgraded, or removed.
		0 packages upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
		Need to get 0 B of archives. After unpacking 0 B will be used.

**Comment by hawkeye116477** [comment]
@dapper27 Certainly you have Ubuntu 14.04. I had problems with building for that old distro. So for now, Xenial is minimum. Soon also all will be migrated to `https://build.opensuse.org/package/show/home:hawkeye116477:waterfox/waterfox` and now will be different packages for different Ubuntu's versions.

**Comment by hawkeye116477** [comment]
@dapper27 Fixed for Trusty, but it's without stylo, but I even have that disabled, cuz it causes problems with some websites.
Remvoe old repo, then try:
```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_14.04/ /' > /etc/apt/sources.list.d/home:hawkeye116477:waterfox.list"
wget -nv https://download.opensuse.org/repositories/home:hawkeye116477:waterfox/xUbuntu_14.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
```

**Comment by dapper27** [comment]
Thanks for the quick updates. It gave me an excuse to bite the bullet and upgrade my server to 16.04, which I had planned to do anyway. Changed to the 16.04 repos and works fine of course!
