### ISSUE TITLE
an apparmor profile

### ISSUE THREAD

**Issue by pirate486743186** [hawkeye116477/waterfox-deb#9]
Here's an apparmor profile. It's nothing fancy, i just modified the existing firefox profile. Apparmor is a kernel security module that restricts program capabilities.

How to package it: You need to uncompress it, github wouldn't let me upload it other wise. The file should be put in /etc/apparmor.d/usr.bin.waterfox .Also, it should be deactivated by default, because it interferes too much with normal usage. To deactivate it, make a symbolic link to the file in /etc/apparmor.d/disable/usr.bin.waterfox .

[usr.bin.waterfox.gz](https://github.com/hawkeye116477/waterfox-deb/files/2498123/usr.bin.waterfox.gz)

**Comment by hawkeye116477** [comment]
Uploaded to OBS, will be in next version.

**Comment by hawkeye116477** [comment]
I see also that I probably need to add „abstraction".
```
# This file is updated by 'aa-update-browser' and may be overwritten on
# upgrades.
#
# For site-specific adjustments, please see /etc/apparmor.d/local/<binary>

#include <abstractions/ubuntu-browsers.d/plugins-common>
#include <abstractions/ubuntu-browsers.d/mailto>
#include <abstractions/ubuntu-browsers.d/multimedia>
#include <abstractions/ubuntu-browsers.d/productivity>
#include <abstractions/ubuntu-browsers.d/java>
#include <abstractions/ubuntu-browsers.d/kde>
#include <abstractions/ubuntu-browsers.d/text-editors>
#include <abstractions/ubuntu-browsers.d/ubuntu-integration>
#include <abstractions/ubuntu-browsers.d/user-files>

/usr/lib/waterfox/kwaterfoxhelper Cxr -> sanitized_helper,
```

I hope that should be good, ubuntu-integration has line with kmozillahelper, so I added to the end of waterfox abstraction similar line for kwaterfoxhelper :smile:.

**Comment by pirate486743186** [comment]
at line 82, leave the original. It's indeed firefox specific locations (xul stuff... gre?).
-  # waterfox specific
+  # firefox specific

move bellow the /etc/waterfox stuff
# waterfox specific
 /etc/waterfox*/ r,
 /etc/waterfox*/** r,

more serious, a post install error:
dpkg: error processing package waterfox (--configure):
 installed waterfox package post-installation script subprocess returned error exit status 10

It failed to create the new files :/
local/usr.bin.waterfox
abstractions/ubuntu-browsers.d/firefox

I didn't see anything wrong with it...

**Comment by hawkeye116477** [comment]
> dpkg: error processing package waterfox (--configure):
> installed waterfox package post-installation script subprocess returned error exit status 10
> 
> It failed to create the new files :/
> local/usr.bin.waterfox
> abstractions/ubuntu-browsers.d/firefox
> 
> I didn't see anything wrong with it...

It's probably problem with templates file. Apparently, by mistake, I copied it from the waterfox-kde directory and that line was bad => `Template: waterfox-kde/locales`, should be waterfox/locales instead of that :smile:.
